version: "2"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
      - "2003:2003"
    volumes:
      - "./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_DB=archive
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  grafana:
    image: grafana/grafana:master
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana:/etc/grafana/provisioning"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
